---
- name: Vuln_adcs_template_control.yml
  hosts: all
  tasks:
    - name: Wait for shared folder to be available
      ansible.windows.win_stat:
        path: C:\vagrant\scripts\red\vuln_kerberos_properties_preauth_priv.ps1
      register: shared_folder_check
      until: shared_folder_check.stat.exists
      retries: 10
      delay: 10

    - name: Execute vuln_kerberos_properties_preauth_priv.ps1
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\vagrant\scripts\red\vuln_kerberos_properties_preauth_priv.ps1
